name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Test Package
        run: npm run test
      - name: Build Package
        run: npm run build